
name: Build and deploy azure function - alerty

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTION_APP_NAME: alerty
  PACKAGE_DIRECTORY: '.'
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'maven'

      - name: 'Maven build'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd

      - name: 'Publish to azure functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ env.AZURE_FUNCTION_APP_NAME }}'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
